# Generated by Django 5.0.2 on 2024-05-01 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fosterable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='animal_adoption_app.animal')),
                ('species', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('wingspan', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='animal_adoption_app.animal')),
                ('breed', models.CharField(max_length=100)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('age', models.IntegerField()),
                ('personality', models.TextField()),
                ('up_to_date_on_vaccines', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='animal_adoption_app.animal')),
                ('breed', models.CharField(max_length=100)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('age', models.IntegerField()),
                ('personality', models.TextField()),
                ('up_to_date_on_vaccines', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='animal_adoption_app.animal')),
                ('species', models.CharField(max_length=100)),
                ('length', models.IntegerField()),
                ('food', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lizard',
            fields=[
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='animal_adoption_app.animal')),
                ('species', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('temperature', models.IntegerField()),
            ],
        ),
    ]
