# Generated by Django 5.0.2 on 2024-05-01 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_adoption_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='species',
            field=models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Lizard', 'Lizard'), ('Bird', 'Bird'), ('Fish', 'Fish')], default='Dog', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='fish',
            name='length',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
