# Generated by Django 5.0.2 on 2024-05-01 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal_adoption_app', '0002_animal_species_alter_animal_name_alter_fish_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='species',
        ),
    ]
