# Generated by Django 5.0.2 on 2024-05-01 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_adoption_app', '0003_remove_animal_species'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='animal',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bird',
            name='animal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='bird', serialize=False, to='animal_adoption_app.animal'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='animal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cat', serialize=False, to='animal_adoption_app.animal'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='animal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='dog', serialize=False, to='animal_adoption_app.animal'),
        ),
        migrations.AlterField(
            model_name='fish',
            name='animal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='fish', serialize=False, to='animal_adoption_app.animal'),
        ),
        migrations.AlterField(
            model_name='lizard',
            name='animal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='lizard', serialize=False, to='animal_adoption_app.animal'),
        ),
    ]
