# Generated by Django 5.0.2 on 2024-05-01 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_adoption_app', '0004_animal_content_type_animal_object_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='object_id',
        ),
        migrations.AlterField(
            model_name='bird',
            name='animal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='animal_adoption_app.animal'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='animal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='animal_adoption_app.animal'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='animal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='animal_adoption_app.animal'),
        ),
        migrations.AlterField(
            model_name='fish',
            name='animal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='animal_adoption_app.animal'),
        ),
        migrations.AlterField(
            model_name='lizard',
            name='animal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='animal_adoption_app.animal'),
        ),
    ]
