# Generated by Django 5.0.2 on 2024-05-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_adoption_app', '0005_remove_animal_content_type_remove_animal_object_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='image_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
