# Generated by Django 5.0.2 on 2024-05-01 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_adoption_app', '0006_animal_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='shelter',
            field=models.CharField(choices=[('Homeward Animal Shelter', 'Homeward Animal Shelter'), ('Cats Cradle Shelter Inc', 'Cats Cradle Shelter Inc'), ('Minn-Kota PAAWS', 'Minn-Kota PAAWS')], default='Homeward Animal Shelter', max_length=100),
            preserve_default=False,
        ),
    ]
